/* Generated by Frama-C */
typedef int bool;
int Cur_Vertical_Sep;
bool High_Confidence;
bool Two_of_Three_Reports_Valid;
int Own_Tracked_Alt;
int Own_Tracked_Alt_Rate;
int Other_Tracked_Alt;
int Alt_Layer_Value;
int Positive_RA_Alt_Thresh[4];
int Up_Separation;
int Down_Separation;
int Other_RAC;
int Other_Capability;
int Climb_Inhibit;
bool Own_Below_Threat(void);

bool Own_Above_Threat(void);

void initialize(void)
{
  Positive_RA_Alt_Thresh[0] = 400;
  Positive_RA_Alt_Thresh[1] = 500;
  Positive_RA_Alt_Thresh[2] = 640;
  Positive_RA_Alt_Thresh[3] = 740;
  return;
}

int ALIM(void)
{
  int __retres;
  __retres = Positive_RA_Alt_Thresh[Alt_Layer_Value];
  return __retres;
}

int Inhibit_Biased_Climb(void)
{
  int __retres;
  pc_label(Climb_Inhibit == 1,2,"CC");
  pc_label(Climb_Inhibit != 1,1,"CC");
  pc_label(Climb_Inhibit != 1,53,"MCC");
  pc_label(Climb_Inhibit == 1,54,"MCC");
  if (Climb_Inhibit == 1) {
    __retres = Up_Separation + 100;
    goto return_label;
  }
  else {
    __retres = Up_Separation;
    goto return_label;
  }
  return_label: return __retres;
}

bool Non_Crossing_Biased_Climb(void)
{
  int upward_preferred;
  bool result;
  bool aux_bool;
  int aux_int;
  int tmp;
  {
    /*sequence*/
    tmp = Inhibit_Biased_Climb();
    upward_preferred = tmp > Down_Separation;
  }
  pc_label(upward_preferred,10,"CC");
  pc_label(! upward_preferred,9,"CC");
  pc_label(! upward_preferred,61,"MCC");
  pc_label(upward_preferred,62,"MCC");
  if (upward_preferred) {
    aux_bool = Own_Below_Threat();
    aux_int = ALIM();
    result = (! aux_bool || (aux_bool && ! (Down_Separation >= aux_int))) != 0;
  }
  else {
    int tmp_2;
    bool tmp_0;
    {
      /*sequence*/
      tmp_0 = Own_Above_Threat();
      pc_label(tmp_0,8,"CC");
      pc_label(! tmp_0,7,"CC");
      pc_label(! tmp_0,59,"MCC");
      pc_label(tmp_0,60,"MCC");
      if (tmp_0) {
        pc_label(Cur_Vertical_Sep >= 300,6,"CC");
        pc_label(Cur_Vertical_Sep < 300,5,"CC");
        pc_label(Cur_Vertical_Sep < 300,57,"MCC");
        pc_label(Cur_Vertical_Sep >= 300,58,"MCC");
        if (Cur_Vertical_Sep >= 300) {
          int tmp_1;
          {
            /*sequence*/
            tmp_1 = ALIM();
            ;
          }
          pc_label(Up_Separation >= tmp_1,4,"CC");
          pc_label(Up_Separation < tmp_1,3,"CC");
          pc_label(Up_Separation < tmp_1,55,"MCC");
          pc_label(Up_Separation >= tmp_1,56,"MCC");
          if (Up_Separation >= tmp_1) tmp_2 = 1; else tmp_2 = 0;
        }
        else tmp_2 = 0;
      }
      else tmp_2 = 0;
      result = tmp_2;
    }
  }
  return result;
}

bool Non_Crossing_Biased_Descend(void)
{
  int upward_preferred;
  bool result;
  int tmp;
  {
    /*sequence*/
    tmp = Inhibit_Biased_Climb();
    upward_preferred = tmp > Down_Separation;
  }
  pc_label(upward_preferred,24,"CC");
  pc_label(! upward_preferred,23,"CC");
  pc_label(! upward_preferred,75,"MCC");
  pc_label(upward_preferred,76,"MCC");
  if (upward_preferred) {
    int tmp_2;
    bool tmp_0;
    {
      /*sequence*/
      tmp_0 = Own_Below_Threat();
      pc_label(tmp_0,16,"CC");
      pc_label(! tmp_0,15,"CC");
      pc_label(! tmp_0,67,"MCC");
      pc_label(tmp_0,68,"MCC");
      if (tmp_0) {
        pc_label(Cur_Vertical_Sep >= 300,14,"CC");
        pc_label(Cur_Vertical_Sep < 300,13,"CC");
        pc_label(Cur_Vertical_Sep < 300,65,"MCC");
        pc_label(Cur_Vertical_Sep >= 300,66,"MCC");
        if (Cur_Vertical_Sep >= 300) {
          int tmp_1;
          {
            /*sequence*/
            tmp_1 = ALIM();
            ;
          }
          pc_label(Down_Separation >= tmp_1,12,"CC");
          pc_label(Down_Separation < tmp_1,11,"CC");
          pc_label(Down_Separation < tmp_1,63,"MCC");
          pc_label(Down_Separation >= tmp_1,64,"MCC");
          if (Down_Separation >= tmp_1) tmp_2 = 1; else tmp_2 = 0;
        }
        else tmp_2 = 0;
      }
      else tmp_2 = 0;
      result = tmp_2;
    }
  }
  else {
    int tmp_6;
    bool tmp_3;
    {
      /*sequence*/
      tmp_3 = Own_Above_Threat();
      pc_label(tmp_3,22,"CC");
      pc_label(! tmp_3,21,"CC");
      pc_label(! tmp_3,73,"MCC");
      pc_label(tmp_3,74,"MCC");
      if (tmp_3) {
        bool tmp_4;
        tmp_4 = Own_Above_Threat();
        pc_label(tmp_4,20,"CC");
        pc_label(! tmp_4,19,"CC");
        pc_label(! tmp_4,71,"MCC");
        pc_label(tmp_4,72,"MCC");
        if (tmp_4) {
          int tmp_5;
          {
            /*sequence*/
            tmp_5 = ALIM();
            ;
          }
          pc_label(Up_Separation >= tmp_5,18,"CC");
          pc_label(Up_Separation < tmp_5,17,"CC");
          pc_label(Up_Separation < tmp_5,69,"MCC");
          pc_label(Up_Separation >= tmp_5,70,"MCC");
          if (Up_Separation >= tmp_5) tmp_6 = 1; else tmp_6 = 0;
        }
        else tmp_6 = 0;
      }
      else tmp_6 = 1;
      result = tmp_6;
    }
  }
  return result;
}

bool Own_Below_Threat(void)
{
  bool __retres;
  pc_label(Own_Tracked_Alt < Other_Tracked_Alt,26,"CC");
  pc_label(Own_Tracked_Alt >= Other_Tracked_Alt,25,"CC");
  pc_label(Own_Tracked_Alt >= Other_Tracked_Alt,77,"MCC");
  pc_label(Own_Tracked_Alt < Other_Tracked_Alt,78,"MCC");
  if (Own_Tracked_Alt < Other_Tracked_Alt) {
    __retres = 1;
    goto return_label;
  }
  else {
    __retres = 0;
    goto return_label;
  }
  return_label: return __retres;
}

bool Own_Above_Threat(void)
{
  bool __retres;
  pc_label(Other_Tracked_Alt < Own_Tracked_Alt,28,"CC");
  pc_label(Other_Tracked_Alt >= Own_Tracked_Alt,27,"CC");
  pc_label(Other_Tracked_Alt >= Own_Tracked_Alt,79,"MCC");
  pc_label(Other_Tracked_Alt < Own_Tracked_Alt,80,"MCC");
  if (Other_Tracked_Alt < Own_Tracked_Alt) {
    __retres = 1;
    goto return_label;
  }
  else {
    __retres = 0;
    goto return_label;
  }
  return_label: return __retres;
}

int alt_sep_test(void)
{
  bool enabled;
  bool tcas_equipped;
  bool intent_not_known;
  bool need_upward_RA;
  bool need_downward_RA;
  int alt_sep;
  initialize();
  enabled = ((High_Confidence && Own_Tracked_Alt_Rate <= 600) && Cur_Vertical_Sep > 600) != 0;
  tcas_equipped = Other_Capability == 1;
  intent_not_known = (Two_of_Three_Reports_Valid && Other_RAC == 0) != 0;
  alt_sep = 0;
  pc_label(enabled,52,"CC");
  pc_label(! enabled,51,"CC");
  pc_label(tcas_equipped,50,"CC");
  pc_label(! tcas_equipped,49,"CC");
  pc_label(intent_not_known,48,"CC");
  pc_label(! intent_not_known,47,"CC");
  pc_label(tcas_equipped,46,"CC");
  pc_label(! tcas_equipped,45,"CC");
  pc_label(((! enabled && ! tcas_equipped) && ! intent_not_known) && ! tcas_equipped,
           97,"MCC");
  pc_label(((! enabled && ! tcas_equipped) && ! intent_not_known) && tcas_equipped,
           98,"MCC");
  pc_label(((! enabled && ! tcas_equipped) && intent_not_known) && ! tcas_equipped,
           99,"MCC");
  pc_label(((! enabled && ! tcas_equipped) && intent_not_known) && tcas_equipped,
           100,"MCC");
  pc_label(((! enabled && tcas_equipped) && ! intent_not_known) && ! tcas_equipped,
           101,"MCC");
  pc_label(((! enabled && tcas_equipped) && ! intent_not_known) && tcas_equipped,
           102,"MCC");
  pc_label(((! enabled && tcas_equipped) && intent_not_known) && ! tcas_equipped,
           103,"MCC");
  pc_label(((! enabled && tcas_equipped) && intent_not_known) && tcas_equipped,
           104,"MCC");
  pc_label(((enabled && ! tcas_equipped) && ! intent_not_known) && ! tcas_equipped,
           105,"MCC");
  pc_label(((enabled && ! tcas_equipped) && ! intent_not_known) && tcas_equipped,
           106,"MCC");
  pc_label(((enabled && ! tcas_equipped) && intent_not_known) && ! tcas_equipped,
           107,"MCC");
  pc_label(((enabled && ! tcas_equipped) && intent_not_known) && tcas_equipped,
           108,"MCC");
  pc_label(((enabled && tcas_equipped) && ! intent_not_known) && ! tcas_equipped,
           109,"MCC");
  pc_label(((enabled && tcas_equipped) && ! intent_not_known) && tcas_equipped,
           110,"MCC");
  pc_label(((enabled && tcas_equipped) && intent_not_known) && ! tcas_equipped,
           111,"MCC");
  pc_label(((enabled && tcas_equipped) && intent_not_known) && tcas_equipped,
           112,"MCC");
  if (enabled && ((tcas_equipped && intent_not_known) || ! tcas_equipped)) {
    int tmp_1;
    bool tmp;
    int tmp_4;
    bool tmp_2;
    {
      /*sequence*/
      tmp = Non_Crossing_Biased_Climb();
      pc_label(tmp,32,"CC");
      pc_label(! tmp,31,"CC");
      pc_label(! tmp,83,"MCC");
      pc_label(tmp,84,"MCC");
      if (tmp) {
        bool tmp_0;
        tmp_0 = Own_Below_Threat();
        pc_label(tmp_0,30,"CC");
        pc_label(! tmp_0,29,"CC");
        pc_label(! tmp_0,81,"MCC");
        pc_label(tmp_0,82,"MCC");
        if (tmp_0) tmp_1 = 1; else tmp_1 = 0;
      }
      else tmp_1 = 0;
      need_upward_RA = tmp_1;
    }
    {
      /*sequence*/
      tmp_2 = Non_Crossing_Biased_Descend();
      pc_label(tmp_2,36,"CC");
      pc_label(! tmp_2,35,"CC");
      pc_label(! tmp_2,87,"MCC");
      pc_label(tmp_2,88,"MCC");
      if (tmp_2) {
        bool tmp_3;
        tmp_3 = Own_Above_Threat();
        pc_label(tmp_3,34,"CC");
        pc_label(! tmp_3,33,"CC");
        pc_label(! tmp_3,85,"MCC");
        pc_label(tmp_3,86,"MCC");
        if (tmp_3) tmp_4 = 1; else tmp_4 = 0;
      }
      else tmp_4 = 0;
      need_downward_RA = tmp_4;
    }
    pc_label(need_upward_RA,44,"CC");
    pc_label(! need_upward_RA,43,"CC");
    pc_label(need_downward_RA,42,"CC");
    pc_label(! need_downward_RA,41,"CC");
    pc_label(! need_upward_RA && ! need_downward_RA,93,"MCC");
    pc_label(! need_upward_RA && need_downward_RA,94,"MCC");
    pc_label(need_upward_RA && ! need_downward_RA,95,"MCC");
    pc_label(need_upward_RA && need_downward_RA,96,"MCC");
    if (need_upward_RA && need_downward_RA) alt_sep = 0;
    else {
      pc_label(need_upward_RA,40,"CC");
      pc_label(! need_upward_RA,39,"CC");
      pc_label(! need_upward_RA,91,"MCC");
      pc_label(need_upward_RA,92,"MCC");
      if (need_upward_RA) alt_sep = 1;
      else {
        pc_label(need_downward_RA,38,"CC");
        pc_label(! need_downward_RA,37,"CC");
        pc_label(! need_downward_RA,89,"MCC");
        pc_label(need_downward_RA,90,"MCC");
        if (need_downward_RA) alt_sep = 2; else alt_sep = 0;
      }
    }
  }
  return alt_sep;
}


